reglamentos = {
    0: "SIN REGLAMENTO - NOTIFICACIÓN PREVIA",
    1: "REG (UE) 1407/2013 DE MINIMIS",
    2: "REG (UE) 1408/2013 DE MINIMIS",
    3: "GENERAL DE EXENCIÓN - REG (UE) 651/2014",
    4: "PRODUCCIÓN AGRÍCOLA PRIMARIA - REG (UE) 702/2014",
    5: "PESCA Y ACUICULTURA - REG (UE) 1388/2014",
    6: "REG (UE) 717/2014 DE MINIMIS",
    7: "REG (UE) 360/2012 DE MINIMIS",
    8: "OTROS DISTINTOS DE PRODUCCIÓN AGRÍCOLA PRIMARIA - REG (UE) 702/2014",
    9: "PRODUCCIÓN AGRÍCOLA PRIMARIA - REG (UE) 2022/2472",
    10: "OTROS DISTINTOS DE PRODUCCIÓN ACRÍGOLA PRIMARIA - REG (UE) 2022/2472",
    11: "PESCA Y ACUICULTURA - REG (UE) 2022/2473",
    12: "REG (UE) 2023/2831 DE MINIMIS, GENERAL",
    13: "REG (UE) 2023/2832 DE MINIMIS, SIEG",
    14: "REG (UE) 1408/2013 DE MINIMIS, AGRÍCOLA",
    15: "REG (UE) 717/2014 DE MINIMIS, PESCA Y ACUICULTURA",
    16: "PRODUCCIÓN AGRÍCOLA PRIMARIA - REG (UE) 2022/2472, DE 14 DE DICIEMBRE, DE EXENCIÓN DE NOTIFICACIÓN (VIGENTE DESDE 01-01-2023)",
    17: "REG (UE) 651/2014, DE 17 DE JUNIO, DE EXENCIÓN DE NOTIFICACIÓN",
    18: "OTROS DISTINTOS DE PRODUCCIÓN AGRÍCOLA PRIMARIA -  REG (UE) 702/2014, DE 25 DE JUNIO, DE EXENCIÓN DE NOTIFICACIÓN",
    19: "REG (UE) 1407/2013 DE MINIMIS, GENERAL",
    20: "OTROS DISTINTOS DE PRODUCCIÓN AGRÍCOLA PRIMARIA - REG (UE) 2022/2472, DE 14 DE DICIEMBRE, DE EXENCIÓN DE NOTIFICACIÓN (VIGENTE DESDE 01-01-2023)",
    21: "REG (UE) 2022/2473, DE 14 DE DICIEMBRE, DE EXENCIÓN DE NOTIFICACIÓN (VIGENTE DESDE 01-01-2023)",
    22: "REG (UE) 1388/2014, DE 16 DE DICIEMBRE, DE EXENCIÓN DE NOTIFICACIÓN",
    23: "PRODUCCIÓN AGRÍCOLA PRIMARIA -  REG (UE) 702/2014, DE 25 DE JUNIO, DE EXENCIÓN DE NOTIFICACIÓN"
}


inverted_reglamentos = {v: k for k, v in reglamentos.items()}



finalidades = {
    1: "JUSTICIA",
    2: "DEFENSA",
    3: "SEGURIDAD CIUDADANA E INSTITUCIONES PENITENCIARIAS",
    4: "OTRAS PRESTACIONES ECONÓMICAS",
    5: "SERVICIOS SOCIALES Y PROMOCIÓN SOCIAL",
    6: "FOMENTO DEL EMPLEO",
    7: "DESEMPLEO",
    8: "ACCESO A LA VIVIENDA Y FOMENTO DE LA EDIFICACIÓN",
    9: "SANIDAD",
    10: "EDUCACIÓN",
    11: "CULTURA",
    12: "AGRICULTURA, PESCA Y ALIMENTACIÓN",
    13: "INDUSTRIA Y ENERGÍA",
    14: "COMERCIO, TURISMO Y PYMES",
    15: "SUBVENCIONES AL TRANSPORTE",
    16: "INFRAESTRUCTURAS",
    17: "INVESTIGACIÓN, DESARROLLO E INNOVACIÓN",
    18: "OTRAS ACTUACIONES DE CARÁCTER ECONÓMICO",
    19: "SIN INFORMACION ESPECIFICA",
    20: "COOPERACIÓN INTERNACIONAL PARA EL DESARROLLO Y CULTURAL",
    21: "INFORMACIÓN NO DISPONIBLE"
}

inverted_finalidades = {v: k for k, v in finalidades.items()}



beneficiarios = {
    'PERSONAS FÍSICAS QUE NO DESARROLLAN ACTIVIDAD ECONÓMICA' : 1,
    'PERSONAS JURÍDICAS QUE NO DESARROLLAN ACTIVIDAD ECONÓMICA' : 2,
    'PYME Y PERSONAS FÍSICAS QUE DESARROLLAN ACTIVIDAD ECONÓMICA' : 3,
    'GRAN EMPRESA' : 4,
    'SIN INFORMACION ESPECIFICA' : 5
}


instrumentos = {
    'SUBVENCIÓN Y ENTREGA DINERARIA SIN CONTRAPRESTACIÓN' : 1,
    'PRÉSTAMO' : 2,
    'GARANTÍA' : 4,
    'VENTAJA FISCAL' : 5,
    'APORTACIÓN DE FINANCIACIÓN RIESGO' : 6,
    'OTROS INSTRUMENTOS DE AYUDA' : 7, 
}

patrones = [
    r'^\d{1,2}/\d{2}/\d{4}$',       # dd/mm/yyyy
    r'^\d{4}-\d{2}-\d{2}$',       # yyyy-mm-dd
    r'^\d{2}-\d{2}-\d{4}$',       # dd-mm-yyyy
    r'^\d{2}/\d{2}/\d{4}$',       # mm/dd/yyyy
]



dict_tipe = {
    'Entidad Local' : 1,
    'Comunidad Autonoma' : 2,
    'Administracion del Estado' : 3,
    'Otros' : 4
}
